# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Windows-Publish

on:
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: [windows-latest]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run release

    - name: Upload application installer
      uses: actions/upload-artifact@v2.2.1
      with:
        name: installer
        path: dist/fs-viewer*.msi

    - name: Upload ASAR archive
      uses: actions/upload-artifact@v2.2.1
      with:
        name: asar
        path: dist/win32-unpacked/resources/app.asar

    - name: Upload attribution files
      uses: actions/upload-artifact@v2.2.1
      with:
        name: attributions
        path: build/ATTRIBUTION.*.json
